name: koswat_examples_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-forge::python=3.13
  - conda-forge::pip
  - conda-forge::ipyleaflet
  - conda-forge::ipywidgets
  - conda-forge::ipyfilechooser
  - conda-forge::leafmap
  - conda-forge::voila
  - conda-forge::IPython
  - pip:
    - git+https://github.com/Deltares/koswat.git
    - itables
