name: koswat_examples_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-forge::python=3.13
  - conda-forge::pip
  - ipyleaflet
  - ipywidgets
  - ipyfilechooser
  - leafmap
  - voila
  - IPython
  - pip:
    - git+https://github.com/Deltares/koswat.git
