name: koswat_examples_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-forge::python=3.10
  - conda-forge::pip
  - conda-forge::ipython
  - conda-forge::ipyleaflet
  - conda-forge::ipywidgets
  - conda-forge::ipyfilechooser
  - conda-forge::itables
  - conda-forge::voila
  - pip:
    - git+https://github.com/Deltares/koswat.git
